language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - redesign
rvm:
- 2.4
env:
  global:
  - secure: jK85CCvnLoITiY+bVQgwsx+ggVvWHYv4OPO9FSm5hfuMCrXeUMh/DDHCuyEDx9LKaX/D55Is7AuPcQygu2WLOeVQY43+cxoZUNLG/nYfaCSL0hEFzSJdN4ajAuKGSIQzzS6ctCrCismXkxBZfOtUrTHLzhxBy3T+q7LxCCVgdsauBpGmKcCWVC1CufZ2cFsEfRcuM0cLnO7L5cwnG9IFyq4hoknbkS3kPpqGyrT9KQ7zOy3d9bSu2JWHgQEoUPnFi+EjMbb/lT5LTPCKpGP3kKc10OfDTjXIGs2dxtkiMDPiYnVAiX72Z/47BeIXSjTDF4B0XdxPX7XxtssEnILJU32PjJjn8g653JfthlbpkAJYA3OWC+0MX9qJ6go9UW2Mt105+v91khQ+orJTNimv/8M8F0AuWX1uMRnngYHpuHPMFSuWFI+DtB5KCpCsQ3TIvljzNwg9V/t4OD0zOQYwu5+a30zl0ZNIk4YRXCzYeZqDb2WId7wXYjd3en5+D252GDYqr9U3t3NtPfdvdvT8+84b5HXNsowAPUkQc+IPEFtvm/gnnJCTcE1fU7t/tHcQ2PWjm61p+lzvwy8lzYfC1HGnMeEvi38KJBMcmLWySx3VAJXTxvwX6q4/HREkO5669q0yHMunYmOi5lgfGVqH3rrIGiEqqSnBprZdp+/CATw=
