# Site settings
name: Meyer Group
email: 
author: ud25ysaf

keywords: jekyll, jekyll theme, jekyll framework, stuffthings
description: Witty description here.

# Only use this if you are serving your site via Github Pages
#github:
#  url: "https://meyer-group.github.io"

header: yes
#header_sm: images/banner-small.jpg
#header_med: images/banner-med.jpg
#header_large: images/banner-large.jpg
#header_xl: images/banner-xl.jpg
header_sm: assets/img/picture_webpage_small.jpg
header_med: assets/img/picture_webpage_medium.jpg
header_large: assets/img/picture_webpage_large.jpg
header_xl: assets/img/picture_webpage_xl.jpg


#plugins:
#  - jekyll/scholar

# Exclude our ruby stuff
exclude: [_bibliography, _legacy, .bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized, images/image_optim_cache.yml]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

plugins:
  - jekyll-feed
  - jekyll-scholar

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

scholar:
  # style: https://www.zotero.org/styles/american-chemical-society-with-titles-doi-no-et-al
  style: ./_bibliography/elsevier-with-titles.csl
  sort_by: year
  order: descending
  # group_by: year
  # group_order: descending
  bibliography: bibliography.bib
  bibliography_template: bib
