title: "Meyer Group"
description: "Prof. Dr. Karsten Meyer at Univ. Erlangen-Nuremberg"

url: http://inorganic-chemistry.net
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins: [ 'jekyll-paginate-v2', 'jekyll/scholar' ]

pagination: 
  enabled: true
  debug: false
  per_page: 10
  sort_reverse: true
  indexpage: news
  permalink: /news/:num

exclude: ["_legacy", "node_modules", "Gemfile", "Gemfile.lock", "gulpfile.js", "LICENSE", "package-lock.json", "package.json", "preview.jpg", "README", "import"]

navigation:
 - title: News
   url: /news
 - title: Team
   url: /team
 - title: Research
   url: /research
 - title: Lab
   url: /lab
 - title: Publications
   url: /publications
 - title: Teaching
   url: /teaching

scholar:
  style: https://www.zotero.org/styles/american-chemical-society-with-titles-doi-no-et-al
  sort_by: year
  order: descending
  group_by: year
  group_order: descending
  bibliography: bibliography.bib
  bibliography_template: bib

social:
   github: meyer-group
   email: inorgchem2@fau.de

# google_analytics: "UA-58263416-1"
