title: "Meyer Group"
description: "Prof. Dr. Karsten Meyer at Univ. Erlangen-Nuremberg"

url: http://inorganic-chemistry.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [ 'jekyll-paginate', 'jekyll/scholar' ]
paginate: 5

exclude: ["_legacy", "node_modules", "Gemfile", "Gemfile.lock", "gulpfile.js", "LICENSE", "package-lock.json", "package.json", "preview.jpg", "README", "import"]

navigation:
 - title: News
   url: /index.html
 - title: Team
   url: /team
 - title: Research
   url: /research
 - title: Lab
   url: /lab
 - title: Publications
   url: /publications
 - title: Teaching
   url: /teaching

scholar:
  style: https://www.zotero.org/styles/american-chemical-society-with-titles-doi-no-et-al
  sort_by: year
  order: descending
  group_by: year
  group_order: descending
  bibliography: bibliography.bib
  bibliography_template: bib

social:
   github: meyer-group
   email: inorgchem2@fau.de

# google_analytics: "UA-58263416-1"
