wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Simon_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/web size/Xile PhD 1 web size.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/News/XinjiaoConf.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Jesus_web.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Students/scb.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Students/IngridThesis.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/AlistairFrey_webseite.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupPhotos/group@fau2006.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Vera_news.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Donald_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Students/IngridsPhD.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/JohnBerry_website_2.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/News/DanMindiola.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/AEKing.JPG'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/News/Fe=N triple bond.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Mindiolas.JPG'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/web size/Xile PhD 5 web size.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/JohnBerry_website_1.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Martin_news.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Students/IngridMunich.jpg'
wget 'http://inorganic-chemistry.net/kmpages/news_clip_image002.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Dominik_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/web size/Xile PhD 3 web size.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupPhotos/group2002.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Radim_talk_2_web.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/kisch_verabschiedung.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/MethodsFacilities/lab-renovated.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/StockPhotos/NSFGRFPlogo.gif'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Sascha_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/StockPhotos/topicon.gif'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/MethodsFacilities/lab-solvent system.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/News/Kubiak.JPG'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/MartinaKaess_news.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Koordinationstreffen_1.png'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/News/SmallDickDanMitch.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Laga_webseite.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/web size/Congratulations.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/News/SuzLab.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Matthew_news.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Pascal_Verabschiedung.png'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/wenliangface.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Kisch_TagderChemie_web.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Koordinationstreffen_2.png'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Matthew_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/ally_website.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/NobelPrize.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Students/NewMembers.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/carstenstreb_webpage.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Students/Goodbye Xile.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/k_meyer_honorary_israel_2009.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/News/SmallMikeSailor.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Marat_small_webpage.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Yin_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/CCasey.JPG'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Toni_News.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Julian_news.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Bild_Rau.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Matthias_news.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Chris_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Eva_Poster_web_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/News/OanhJACSTOC.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Alexander_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/IronChemist.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/Boris_Martina.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Soosan_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Angel_klein.jpg'
wget 'http://inorganic-chemistry.net/kmpages/../kmimg/GroupMemberPhotos/Thibault_klein.jpg'
